### ISSUE TITLE
Build Error !

### ISSUE THREAD

**Issue by paulbrasted** [SadBatman/cryptonote-ryo-pool#75]

**Comment by paulbrasted** [comment]
I am running Ubuntu WSL on windows 10 


I get the build using 
git clone https://github.com/SadBatman/cryptonote-sumokoin-pool.git pool-ryo
and then npm update in pool-ryo

I  have latest of all libraries but 1.55 boost was not found ..I have the latest installed 
libboost-all-dev/bionic,now 1.65.1.0ubuntu1 amd64 [installed]

npm update gives the following error ..

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paul/pool-ryo/node_modules/cryptonote-util
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-util@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-util@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2018-11-08T14_52_30_448Z-debug.log

Thanks in anticipation
